---

#  Concept Explanation

Neural networks (like in PyTorch) only understand **numbers**, not text.

So we must convert:

```
"I love NLP" → numbers
```

---

###  Old Method: Bag of Words (BoW)

* Sparse vectors
* No meaning
* No context

Example:

```
"king" ≠ "queen" (no relationship captured)
```

---

###  Solution: Embeddings

A **word embedding** is:

> A dense vector that represents a word’s meaning

Example:

```
"king"   → [0.25, -0.1, 0.8, ...]
"queen"  → [0.27, -0.12, 0.75, ...]
```

 Similar words → similar vectors

---

###  Key Idea

Embedding Layer = a **lookup table** that maps:

```
word_index → dense vector
```

---

#  Why It Matters

Without embeddings:

* Models treat words as **independent tokens**
* No semantic understanding

With embeddings:

* Capture meaning
* Capture similarity
* Enable deep NLP models

 This is the foundation of:

* LSTM
* Transformers
* BERT

---

#  Simple Example (Intuition)

Think of embeddings like:

 A **map of words in space**

* "cat" and "dog" → close together 
* "car" → far away 

So the model understands:

```
cat ≈ dog
cat ≠ car
```


# Import Libraries

In [1]:
import torch
import torch.nn as nn

# Example

In [2]:
sentences = [
    "i love nlp",
    "i love machine learning",
    "nlp is fun"
]

# Build Vocabulary

In [4]:
words = set(" ".join(sentences).split())

word2idx = {word: i for i, word in enumerate(words)}

vocab_size = len(word2idx)
print(word2idx)

{'i': 0, 'love': 1, 'learning': 2, 'is': 3, 'machine': 4, 'fun': 5, 'nlp': 6}


# Convert Sentences to Indices

In [5]:
def encode(sentence):
    return [word2idx[word] for word in sentence.split()]

encoded_sentences = [encode(s) for s in sentences]
print(encoded_sentences)

[[0, 1, 6], [0, 1, 4, 2], [6, 3, 5]]


## Padding

In [6]:
from torch.nn.utils.rnn import pad_sequence

encoded_tensors = [torch.tensor(seq) for seq in encoded_sentences]
padded = pad_sequence(encoded_tensors, batch_first=True)

print(padded)

tensor([[0, 1, 6, 0],
        [0, 1, 4, 2],
        [6, 3, 5, 0]])


## Embedding Layer

In [7]:
embedding_dim = 5

embedding = nn.Embedding(
    num_embeddings=vocab_size,
    embedding_dim=embedding_dim
)

## Apply Embedding

In [8]:
embedded_output = embedding(padded)

print(embedded_output.shape)

torch.Size([3, 4, 5])


# Visualization / Results

In [9]:
print(embedding.weight)

Parameter containing:
tensor([[ 2.8709, -0.2976, -0.7126, -1.1747, -1.9041],
        [ 0.2730, -0.5574,  0.5139, -0.0126,  0.9719],
        [ 1.5850,  0.0825,  0.8193,  0.3740,  0.9025],
        [-1.0020,  0.5743,  0.6112, -0.1018, -0.7777],
        [-0.8488,  0.4919, -0.4608, -0.5619,  1.0808],
        [-0.5712,  0.1766, -0.9811,  1.2792,  0.2975],
        [ 0.5039,  0.3532, -1.0450, -0.4652, -0.0080]], requires_grad=True)


## Compare Words

In [10]:
word = "nlp"
idx = word2idx[word]

print(f"Embedding for '{word}':")
print(embedding.weight[idx])

Embedding for 'nlp':
tensor([ 0.5039,  0.3532, -1.0450, -0.4652, -0.0080],
       grad_fn=<SelectBackward0>)


---

#  Next Notebook: `03_rnn_lstm`

 We will solve this problem:

> Embeddings don’t understand **word order**

Example:

```
"I love you" ≠ "You love I"
```

 Solution → **RNN / LSTM**